gpu01
no change     /pchem-data/meuwly/boittier/home/miniforge3/condabin/conda
no change     /pchem-data/meuwly/boittier/home/miniforge3/bin/conda
no change     /pchem-data/meuwly/boittier/home/miniforge3/bin/conda-env
no change     /pchem-data/meuwly/boittier/home/miniforge3/bin/activate
no change     /pchem-data/meuwly/boittier/home/miniforge3/bin/deactivate
no change     /pchem-data/meuwly/boittier/home/miniforge3/etc/profile.d/conda.sh
no change     /pchem-data/meuwly/boittier/home/miniforge3/etc/fish/conf.d/conda.fish
no change     /pchem-data/meuwly/boittier/home/miniforge3/shell/condabin/Conda.psm1
no change     /pchem-data/meuwly/boittier/home/miniforge3/shell/condabin/conda-hook.ps1
no change     /pchem-data/meuwly/boittier/home/miniforge3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /pchem-data/meuwly/boittier/home/miniforge3/etc/profile.d/conda.csh
no change     /pchem-data/meuwly/boittier/home/.bashrc
No action taken.
/pchem-data/meuwly/boittier/home/miniforge3/envs/jaxe3xcuda11p39/bin/python
GPU ID: 0
restart /pchem-data/meuwly/boittier/home/jaxeq/all_runs/runs11/20240924-141337dcm-2-espw-1000.0-restart-False/best_1000.0_params.pkl
args:
data_dir = /pchem-data/meuwly/boittier/home/jaxeq/
model_dir = model
num_epochs = 5000
learning_rate = 0.0001
batch_size = 1
esp_w = 1000.0
num_epics = 1
n_feat = 16
n_basis = 16
max_degree = 2
n_mp = 2
restart = /pchem-data/meuwly/boittier/home/jaxeq/all_runs/runs11/20240924-141337dcm-2-espw-1000.0-restart-False/best_1000.0_params.pkl
random_seed = 15828
n_dcm = 1
n_gpu = 0
data = qm9-esp40000-0.npz
n_train = 64000
n_valid = 2000
type = dipole
include_pseudotensors = False
[cuda(id=0)]
gpu
[cuda(id=0)]
['/pchem-data/meuwly/boittier/home/jaxeq/dcmnet', '/pchem-data/meuwly/boittier/home/miniforge3/envs/jaxe3xcuda11p39/lib/python39.zip', '/pchem-data/meuwly/boittier/home/miniforge3/envs/jaxe3xcuda11p39/lib/python3.9', '/pchem-data/meuwly/boittier/home/miniforge3/envs/jaxe3xcuda11p39/lib/python3.9/lib-dynload', '/pchem-data/meuwly/boittier/home/miniforge3/envs/jaxe3xcuda11p39/lib/python3.9/site-packages', '/pchem-data/meuwly/boittier/home/jaxeq']
{'features': 16.0, 'max_degree': 2.0, 'num_iterations': 2.0, 'num_basis_functions': 16.0, 'cutoff': 4.0, 'n_dcm': 2.0, 'include_pseudotensors': True}
R (40000, 60, 3)
Z (40000, 60)
N (40000,)
D (40000,)
com (40000, 3)
Dxyz (40000, 3)
mono (40000, 60, 1)
esp (40000, 3200)
id (40000,)
n_grid (40000,)
vdw_surface (40000, 3200, 3)
n_failed: 449
31551 4000.0
creating_mask
39551
/pchem-data/meuwly/boittier/home/jaxeq/all_runs/tests/20240925-143143dcm-2-espw-1000.0-restart-True
epic 1
Preparing batches
..................
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/pchem-data/meuwly/boittier/home/jaxeq/dcmnet/main.py", line 130, in <module>
    params, val = training(
  File "/pchem-data/meuwly/boittier/home/jaxeq/dcmnet/training_dipole.py", line 210, in train_model_dipo
    params, opt_state, loss, global_norm = train_step_dipo(
TypeError: Dtype <U16 is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
